### PR TITLE
Split css out in Tell A Story project

### PR DESCRIPTION
**Pull request by andylolz**
Here’s the trinket I used:
https://trinket.io/html/7bfa446bba

Refs #32.

### CODE REVIEW

**Comment by CodeClubRik** [comment]
Thanks @andylolz  :) Hope it goes (went?) well

**Comment by andylolz** [comment]
It was weirdly cancelled! The school was empty; no mention on the website. Day off because of the weather possibly?!

**Comment by CodeClubRik** [comment]
strange! the same thing almost happened to me today - everyone busy doing other things but didn't tell me!

**Comment by andylolz** [comment]
Haha oh noes!

**Pull request merged**
